### ISSUE TITLE
Carthage build failed with Xcode 8.1

### ISSUE THREAD

**Issue by aalenliang** [Cocoanetics/Kvitto#4]
Build with Xcode 8.1, Swift 3.1, failed with:
'error: 'objc_unretainedPointer' is unavailable: use a __bridge cast instead'

Maybe related to https://github.com/Cocoanetics/DTFoundation/pull/107

Here is the full output:

*** Building scheme "Kvitto" in Kvitto.xcodeproj
** CLEAN FAILED **

The following build commands failed:
	Check dependencies
(1 failure)
** BUILD FAILED **

The following build commands failed:
	CompileC ../Library/Developer/Xcode/DerivedData/Kvitto-fwlzvoaknmfsvueudpxmjrwsyrzz/Build/Intermediates/DTFoundation.build/Release-iphoneos/DTFoundation\ (iOS).build/Objects-normal/armv7/NSObject+DTRuntime.o Core/Source/Runtime/NSObject+DTRuntime.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
../Carthage/Checkouts/Kvitto/Externals/DTFoundation/Core/Source/Runtime/NSObject+DTRuntime.m:51:38: error: 'objc_unretainedPointer' is unavailable: use a __bridge cast instead
A shell task (/usr/bin/xcrun xcodebuild -project ../Carthage/Checkouts/Kvitto/Kvitto.xcodeproj -scheme Kvitto -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** CLEAN FAILED **

The following build commands failed:
	Check dependencies
(1 failure)
** BUILD FAILED **

The following build commands failed:
	CompileC ../Developer/Xcode/DerivedData/Kvitto-fwlzvoaknmfsvueudpxmjrwsyrzz/Build/Intermediates/DTFoundation.build/Release-iphoneos/DTFoundation\ (iOS).build/Objects-normal/armv7/NSObject+DTRuntime.o Core/Source/Runtime/NSObject+DTRuntime.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

**Comment by odrobnik** [comment]
This has been fixed in recent DTFoundation releases.
